name: gtads_sigmob
description: 为GTAds提供Singmob广告支持
version: 0.0.1
homepage: https://github.com/gstory0404/GTAds/tree/master/gtads_sigmob

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  # 广告基础库 必须引入
  gtads: ^0.0.6
#  gtads:
#    path: ../gtads
  # Sigmob
  sigmobad: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.gstory.gtads_sigmob
        pluginClass: GtadsSigmobPlugin
      ios:
        pluginClass: GtadsSigmobPlugin
