name: gtads_csj
description: GTAds-穿山甲广告支持
version: 0.0.6
homepage: https://github.com/gstory0404/GTAds/blob/master/gtads_csj

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_unionad: ^1.3.13
#  gtads:
#    path: ../gtads
  gtads: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.gtads_csj
        pluginClass: GtadsCsjPlugin
      ios:
        pluginClass: GtadsCsjPlugin